#!/usr/bin/env python3
"""Step 4: Write Packmol input and invoke the packmol binary."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

from common import load_manifest, save_manifest


def resolve_packmol_bin(cli: str | None) -> str:
    if cli:
        return cli
    env = os.environ.get("PACKMOL_BINARY", "").strip()
    if env:
        return env
    w = shutil.which("packmol")
    if w:
        return w
    raise RuntimeError(
        "packmol executable not found. Install Packmol and ensure it is on PATH, "
        "or set PACKMOL_BINARY / pass --packmol-binary."
    )


def write_inp(
    dest: Path,
    *,
    polymer_pdb: Path,
    n_chains: int,
    box: tuple[float, float, float],
    tolerance: float,
    seed: int,
    extra_structures: list[tuple[Path, int]],
) -> None:
    x, y, z = box
    lines = [
        "# Generated by polymer-build step04",
        f"tolerance {tolerance}",
        "filetype pdb",
        "output packed.pdb",
        "",
        f"structure {polymer_pdb.name}",
        f"  number {int(n_chains)}",
        f"  inside box 0. 0. 0. {x:.6f} {y:.6f} {z:.6f}",
        "end structure",
        "",
    ]
    for path, count in extra_structures:
        lines.extend(
            [
                f"structure {path.name}",
                f"  number {int(count)}",
                f"  inside box 0. 0. 0. {x:.6f} {y:.6f} {z:.6f}",
                "end structure",
                "",
            ]
        )
    lines.append(f"seed {int(seed)}")
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="polymer-build step04: Packmol packing")
    ap.add_argument("--work-dir", type=Path, required=True)
    ap.add_argument("--polymer-pdb", type=Path, default=None)
    ap.add_argument("--n-chains", type=int, default=4)
    ap.add_argument("--box", type=float, nargs=3, default=(40.0, 40.0, 40.0))
    ap.add_argument("--tolerance", type=float, default=2.0)
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--packmol-binary", type=str, default=None)
    ap.add_argument(
        "--extra-pdb",
        action="append",
        default=[],
        metavar="PATHxCOUNT",
        help="Additional species as pathxinteger, e.g. water.pdbx200",
    )
    args = ap.parse_args()
    work_dir: Path = args.work_dir
    work_dir.mkdir(parents=True, exist_ok=True)

    polymer = args.polymer_pdb or Path(load_manifest(work_dir).get("step03_polymer_pdb", work_dir / "polymer_chain.pdb"))
    if not polymer.is_file():
        polymer = work_dir / "polymer_chain.pdb"
    if not polymer.is_file():
        print(f"step04: polymer PDB not found (got {polymer})", file=sys.stderr)
        return 2

    extras: list[tuple[Path, int]] = []
    for spec in args.extra_pdb:
        if "x" not in spec.lower():
            print(f"step04: --extra-pdb must look like water.pdbx200, got {spec!r}", file=sys.stderr)
            return 2
        left, right = spec.lower().rsplit("x", 1)
        path = Path(left)
        count = int(right)
        if not path.is_file():
            print(f"step04: extra pdb not found: {path}", file=sys.stderr)
            return 2
        extras.append((path, count))

    local_polymer = work_dir / polymer.name
    if polymer.resolve() != local_polymer.resolve():
        local_polymer.write_bytes(polymer.read_bytes())
        polymer_use = local_polymer
    else:
        polymer_use = polymer

    extra_local: list[tuple[Path, int]] = []
    for path, count in extras:
        lp = work_dir / path.name
        if path.resolve() != lp.resolve():
            lp.write_bytes(path.read_bytes())
        extra_local.append((lp, count))

    inp = work_dir / "packmol.inp"
    write_inp(
        inp,
        polymer_pdb=polymer_use,
        n_chains=args.n_chains,
        box=(float(args.box[0]), float(args.box[1]), float(args.box[2])),
        tolerance=float(args.tolerance),
        seed=int(args.seed),
        extra_structures=extra_local,
    )

    try:
        bin_path = resolve_packmol_bin(args.packmol_binary)
    except RuntimeError as e:
        print(f"step04: {e}", file=sys.stderr)
        return 4

    proc = subprocess.run(
        [bin_path, inp.name],
        cwd=str(work_dir),
        capture_output=True,
        text=True,
    )
    log = work_dir / "packmol.stdout.log"
    log.write_text(proc.stdout + "\n--- stderr ---\n" + proc.stderr, encoding="utf-8")
    if proc.returncode != 0:
        print(f"step04: packmol failed (exit {proc.returncode}). See {log}", file=sys.stderr)
        return proc.returncode or 4

    packed = work_dir / "packed.pdb"
    if not packed.is_file():
        print(f"step04: expected output missing: {packed}", file=sys.stderr)
        return 4

    save_manifest(
        work_dir,
        {
            "step04_packmol_inp": str(inp.resolve()),
            "step04_packed_pdb": str(packed.resolve()),
            "step04_box": list(map(float, args.box)),
            "step04_n_chains": int(args.n_chains),
        },
    )
    print(f"wrote {packed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
