// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// SPDX-License-Identifier: MIT

import type { Edge, Node } from "@xyflow/react";

type OutputFieldRow = { name?: string; type?: string };
type StartInputRow = { key?: string; type?: string };

export function getNodeIdentifier(node: Node): string {
  const identifier = node.data?.taskName || node.data?.nodeName || node.data?.label || node.id;
  return typeof identifier === "string" ? identifier : String(identifier);
}

/** Direct upstream nodes connected by an incoming edge. */
export function getDirectUpstreamNodes(
  currentNodeId: string,
  nodes: Node[],
  edges: Edge[],
): Node[] {
  const sourceIds = edges
    .filter((e) => e.target === currentNodeId)
    .map((e) => e.source);
  const idSet = new Set(sourceIds);
  return nodes.filter((n) => idSet.has(n.id));
}

export function getDirectUpstreamNodeIds(currentNodeId: string, edges: Edge[]): Set<string> {
  return new Set(
    edges.filter((e) => e.target === currentNodeId).map((e) => e.source),
  );
}

/** All ancestor nodes reachable by following incoming edges (BFS, nearest first). */
export function getTransitiveUpstreamNodes(
  currentNodeId: string,
  nodes: Node[],
  edges: Edge[],
): Node[] {
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const visited = new Set<string>();
  const order: string[] = [];
  const queue = edges
    .filter((e) => e.target === currentNodeId)
    .map((e) => e.source);

  while (queue.length > 0) {
    const id = queue.shift()!;
    if (visited.has(id)) continue;
    visited.add(id);
    order.push(id);
    for (const e of edges) {
      if (e.target === id && !visited.has(e.source)) {
        queue.push(e.source);
      }
    }
  }

  return order.map((id) => byId.get(id)).filter((n): n is Node => n != null);
}

/** Template variable lines for one upstream node (File fields first). */
export function upstreamTemplateRefs(node: Node): string[] {
  const id = getNodeIdentifier(node);
  const outputFields = (node.data?.outputFields || node.data?.output_fields || []) as OutputFieldRow[];

  if (node.type === "start") {
    const refs: string[] = [];
    const startInputs = node.data?.startInputs as StartInputRow[] | undefined;
    if (Array.isArray(startInputs)) {
      for (const row of startInputs) {
        if (row?.key?.trim() && row.type === "path") {
          refs.push(`{{${id}.output.${row.key.trim()}}}`);
        }
      }
    }
    if (refs.length > 0) return refs;
    return [`{{${id}.input}}`];
  }

  if (Array.isArray(outputFields) && outputFields.length > 0) {
    const fileFields = outputFields.filter((f) => f?.name && f.type === "File");
    const otherFields = outputFields.filter((f) => f?.name && f.type !== "File");
    const refs = [...fileFields, ...otherFields].map(
      (f) => `{{${id}.output.${f.name}}}`,
    );
    if (refs.length > 0) return refs;
  }

  return [`{{${id}.output}}`];
}

/** Default user prompt referencing direct upstream outputs only (not transitive ancestors). */
export function buildDefaultLlmPromptFromUpstream(
  currentNodeId: string,
  nodes: Node[],
  edges: Edge[],
): string {
  const upstream = getDirectUpstreamNodes(currentNodeId, nodes, edges);
  if (upstream.length === 0) return "";

  const lines: string[] = [];
  for (const node of upstream) {
    const refs = upstreamTemplateRefs(node);
    lines.push(...refs);
  }

  if (lines.length === 1) {
    return `请根据上游输入处理任务：\n${lines[0]}`;
  }
  return `请根据上游输入处理任务：\n${lines.join("\n")}`;
}

export function isAutoGeneratedLlmPrompt(
  prompt: string,
  currentNodeId: string,
  nodes: Node[],
  edges: Edge[],
): boolean {
  const trimmed = prompt.trim();
  if (!trimmed) return true;
  const expected = buildDefaultLlmPromptFromUpstream(currentNodeId, nodes, edges).trim();
  return trimmed === expected;
}

export function resolveLlmPromptSource(
  nodeData: Record<string, unknown>,
  currentNodeId: string,
  nodes: Node[],
  edges: Edge[],
): "auto" | "manual" {
  const explicit = nodeData.llmPromptSource;
  if (explicit === "manual" || explicit === "auto") return explicit;
  const prompt = typeof nodeData.llmPrompt === "string" ? nodeData.llmPrompt : "";
  return isAutoGeneratedLlmPrompt(prompt, currentNodeId, nodes, edges) ? "auto" : "manual";
}

function getDescendantNodeIds(fromIds: Iterable<string>, edges: Edge[]): Set<string> {
  const result = new Set<string>();
  const queue = [...fromIds];
  while (queue.length > 0) {
    const id = queue.shift()!;
    for (const e of edges) {
      if (e.source === id && !result.has(e.target)) {
        result.add(e.target);
        queue.push(e.target);
      }
    }
  }
  return result;
}

/** LLM node ids that should refresh auto prompt after an edge change at `anchorTargets`. */
export function llmNodeIdsAffectedByEdgeChange(
  anchorTargets: Iterable<string>,
  nodes: Node[],
  edges: Edge[],
): Set<string> {
  const affected = new Set(getDescendantNodeIds(anchorTargets, edges));
  for (const id of anchorTargets) {
    affected.add(id);
  }
  const llmIds = new Set<string>();
  for (const n of nodes) {
    if (n.type === "llm" && affected.has(n.id)) {
      llmIds.add(n.id);
    }
  }
  return llmIds;
}

export function syncAutoLlmPromptsOnNodes(
  nodes: Node[],
  edges: Edge[],
  targetNodeIds: Iterable<string>,
): Node[] {
  const targetSet = new Set(targetNodeIds);
  if (targetSet.size === 0) return nodes;

  return nodes.map((node) => {
    if (node.type !== "llm" || !targetSet.has(node.id)) return node;
    const data = (node.data || {}) as Record<string, unknown>;
    if (resolveLlmPromptSource(data, node.id, nodes, edges) !== "auto") return node;
    const nextPrompt = buildDefaultLlmPromptFromUpstream(node.id, nodes, edges);
    return {
      ...node,
      data: {
        ...data,
        llmPrompt: nextPrompt,
        llmPromptSource: "auto",
      },
    };
  });
}
