import { describe, expect, it } from "vitest";
import type { Edge, Node } from "@xyflow/react";

import {
  buildDefaultLlmPromptFromUpstream,
  getDirectUpstreamNodes,
  getTransitiveUpstreamNodes,
  isAutoGeneratedLlmPrompt,
  resolveLlmPromptSource,
  syncAutoLlmPromptsOnNodes,
} from "@/components/workflow/editor/utils/upstream";

const nodes: Node[] = [
  { id: "start", type: "start", position: { x: 0, y: 0 }, data: { taskName: "开始" } },
  {
    id: "a",
    type: "llm",
    position: { x: 0, y: 0 },
    data: {
      taskName: "POSCAR",
      outputFields: [{ name: "poscar", type: "File" }],
    },
  },
  {
    id: "b",
    type: "llm",
    position: { x: 0, y: 0 },
    data: {
      taskName: "POTCAR",
      outputFields: [{ name: "potcar", type: "File" }],
    },
  },
  { id: "relax", type: "llm", position: { x: 0, y: 0 }, data: { taskName: "弛豫" } },
];

const edges: Edge[] = [
  { id: "e1", source: "start", target: "a" },
  { id: "e2", source: "a", target: "b" },
  { id: "e3", source: "b", target: "relax" },
];

describe("getTransitiveUpstreamNodes", () => {
  it("includes ancestors beyond direct parent", () => {
    const upstream = getTransitiveUpstreamNodes("relax", nodes, edges);
    expect(upstream.map((n) => n.id)).toEqual(["b", "a", "start"]);
  });

  it("direct upstream is only immediate parent", () => {
    expect(getDirectUpstreamNodes("relax", nodes, edges).map((n) => n.id)).toEqual(["b"]);
  });
});

describe("buildDefaultLlmPromptFromUpstream", () => {
  it("references output file fields for direct upstream only", () => {
    const prompt = buildDefaultLlmPromptFromUpstream("relax", nodes, edges);
    expect(prompt).toContain("{{POTCAR.output.potcar}}");
    expect(prompt).not.toContain("{{POSCAR.output.poscar}}");
    expect(prompt).not.toContain("{{开始.input}}");
  });
});

describe("llmPromptSource", () => {
  it("detects auto-generated prompt", () => {
    const auto = buildDefaultLlmPromptFromUpstream("relax", nodes, edges);
    expect(isAutoGeneratedLlmPrompt(auto, "relax", nodes, edges)).toBe(true);
    expect(
      resolveLlmPromptSource({ llmPrompt: auto }, "relax", nodes, edges),
    ).toBe("auto");
    expect(
      resolveLlmPromptSource({ llmPrompt: "custom", llmPromptSource: "manual" }, "relax", nodes, edges),
    ).toBe("manual");
  });
});

describe("syncAutoLlmPromptsOnNodes", () => {
  it("updates auto llm nodes when edges change", () => {
    const llmNodes = nodes.map((n) =>
      n.id === "relax"
        ? { ...n, data: { ...n.data, llmPromptSource: "auto", llmPrompt: "" } }
        : n,
    );
    const synced = syncAutoLlmPromptsOnNodes(llmNodes, edges, ["relax"]);
    const relax = synced.find((n) => n.id === "relax");
    expect(relax?.data?.llmPrompt).toContain("{{POTCAR.output.potcar}}");
  });
});
