"""
Moltemplate 工具封装

LAMMPS 分子/力场拓扑构建工具
"""

from __future__ import annotations
from typing import Optional, List, Dict, Any, Union
from pathlib import Path
import subprocess
import tempfile
import shutil

from modeling.core.structure import Structure


class MoltemplateTools:
    """
    Moltemplate 工具封装

    Moltemplate 是用于构建 LAMMPS 输入文件的通用工具

    功能:
    - 从模板构建复杂分子系统
    - 自动检测键角/二面角
    - 支持多种力场 (OPLSAA, GAFF, MARTINI, TraPPE)
    - 生成 LAMMPS DATA 和输入脚本

    参考: https://www.moltemplate.org/
    """

    _moltemplate_available: Optional[bool] = None
    _moltemplate_path: Optional[str] = None

    # 支持的力场
    SUPPORTED_FORCEFIELDS = [
        "oplsaa",      # OPLS-AA
        "gaff",        # AMBER GAFF
        "gaff2",       # AMBER GAFF2
        "martini",     # MARTINI 粗粒化
        "trappe",      # TraPPE
        "compass",     # COMPASS
    ]

    @classmethod
    def is_available(cls) -> bool:
        """检查 Moltemplate 是否可用"""
        if cls._moltemplate_available is None:
            cls._moltemplate_path = shutil.which("moltemplate.sh")
            cls._moltemplate_available = cls._moltemplate_path is not None
        return cls._moltemplate_available

    @classmethod
    def require_moltemplate(cls):
        """确保 Moltemplate 可用"""
        if not cls.is_available():
            raise RuntimeError(
                "此功能需要 Moltemplate。请安装: pip install moltemplate"
            )

    # ==================== 主要功能 ====================

    @classmethod
    def build_system(
        cls,
        lt_file: str,
        output_prefix: str = "system",
        working_dir: Optional[str] = None,
    ) -> Dict[str, Path]:
        """
        从 .lt 文件构建 LAMMPS 系统

        Args:
            lt_file: Moltemplate .lt 文件路径
            output_prefix: 输出文件前缀
            working_dir: 工作目录

        Returns:
            生成文件的路径字典
        """
        cls.require_moltemplate()

        work_path = Path(working_dir) if working_dir else Path(lt_file).parent

        cmd = [
            cls._moltemplate_path,
            "-atomstyle", "full",
            "-pdb", f"{output_prefix}.pdb",
            lt_file,
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=work_path,
            timeout=600,
        )

        if result.returncode != 0:
            raise RuntimeError(f"Moltemplate 执行失败:\n{result.stderr}")

        # 返回生成的文件
        return {
            "data": work_path / f"{output_prefix}.data",
            "in_init": work_path / f"{output_prefix}.in.init",
            "in_settings": work_path / f"{output_prefix}.in.settings",
            "pdb": work_path / f"{output_prefix}.pdb",
        }

    @classmethod
    def generate_lt_file(
        cls,
        structure: Structure,
        forcefield: str = "oplsaa",
        molecule_name: str = "MOL",
    ) -> str:
        """
        为结构生成 .lt 文件内容

        Args:
            structure: 输入结构
            forcefield: 力场名称
            molecule_name: 分子名称

        Returns:
            .lt 文件内容字符串

        TODO: 实现完整的 .lt 文件生成
        """
        if forcefield.lower() not in cls.SUPPORTED_FORCEFIELDS:
            raise ValueError(
                f"不支持的力场: {forcefield}。"
                f"支持: {cls.SUPPORTED_FORCEFIELDS}"
            )

        # 生成基本的 .lt 文件框架
        lines = [
            f"# Generated by modeling toolkit",
            f"# Forcefield: {forcefield}",
            "",
            f'import "{forcefield}.lt"',
            "",
            f"{molecule_name} {{",
            "",
            "  # Atoms",
            "  write('Data Atoms') {",
        ]

        # 写入原子
        for i, (pos, sym) in enumerate(zip(structure.positions, structure.symbols)):
            atom_type = f"@atom:{sym}"  # 简化处理
            lines.append(
                f"    $atom:{sym}{i+1} $mol:. {atom_type} 0.0 "
                f"{pos[0]:.4f} {pos[1]:.4f} {pos[2]:.4f}"
            )

        lines.extend([
            "  }",
            "",
            "  # Bonds (TODO: auto-detect)",
            "  write('Data Bonds') {",
            "  }",
            "",
            "}",
        ])

        return "\n".join(lines)

    # ==================== 力场模板 ====================

    @classmethod
    def get_forcefield_template(cls, forcefield: str) -> str:
        """
        获取力场模板文件路径

        Args:
            forcefield: 力场名称

        Returns:
            模板文件路径
        """
        cls.require_moltemplate()

        # Moltemplate 内置力场通常在安装目录
        # 这里返回力场导入语句
        return f'import "{forcefield.lower()}.lt"'

    @classmethod
    def list_available_forcefields(cls) -> List[str]:
        """列出可用的力场"""
        return cls.SUPPORTED_FORCEFIELDS.copy()

    # ==================== 系统构建辅助 ====================

    @classmethod
    def create_box_lt(
        cls,
        box_size: tuple,
        molecules: Dict[str, int],
    ) -> str:
        """
        生成系统盒子的 .lt 文件

        Args:
            box_size: 盒子尺寸 (lx, ly, lz) (Å)
            molecules: {分子名: 数量} 字典

        Returns:
            system.lt 文件内容
        """
        lx, ly, lz = box_size

        lines = [
            "# System definition",
            "",
            "write_once('Data Boundary') {",
            f"  0 {lx} xlo xhi",
            f"  0 {ly} ylo yhi",
            f"  0 {lz} zlo zhi",
            "}",
            "",
        ]

        # 导入分子
        for mol_name in molecules:
            lines.append(f'import "{mol_name}.lt"')

        lines.append("")

        # 创建分子实例
        for mol_name, count in molecules.items():
            for i in range(count):
                lines.append(f"{mol_name}_{i} = new {mol_name}")

        return "\n".join(lines)

    # ==================== 与 Packmol 集成 ====================

    @classmethod
    def from_packmol(
        cls,
        packmol_output: str,
        forcefield: str = "oplsaa",
        output_prefix: str = "system",
    ) -> Dict[str, Path]:
        """
        从 Packmol 输出创建 LAMMPS 文件

        Args:
            packmol_output: Packmol 输出的 PDB 文件
            forcefield: 力场
            output_prefix: 输出前缀

        Returns:
            生成文件的路径

        TODO: 实现 Packmol -> Moltemplate 工作流
        """
        raise NotImplementedError(
            "Packmol -> Moltemplate 工作流需要额外配置"
        )
