"""
StructureWriter - 结构文件写入器
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional
import numpy as np

from modeling.core.structure import Structure


class StructureWriter:
    """
    结构文件写入器

    支持格式:
    - PDB (纯 Python)
    - XYZ (纯 Python)
    - POSCAR (纯 Python)
    - Gaussian .gjf/.com (纯 Python)
    - CIF (需要 ASE)
    - LAMMPS data (需要 ASE)
    - GRO (需要 ASE)
    """

    def write(
        self,
        structure: Structure,
        filepath: str,
        format: Optional[str] = None
    ):
        """
        写入结构文件

        Args:
            structure: Structure对象
            filepath: 输出文件路径
            format: 文件格式，None则根据扩展名判断
        """
        path = Path(filepath)

        if format is None:
            format = self._detect_format(path)

        writer_method = getattr(self, f"_write_{format}", None)
        if writer_method is None:
            raise ValueError(f"不支持的输出格式: {format}")

        writer_method(structure, path)

    def _detect_format(self, path: Path) -> str:
        """检测格式"""
        ext = path.suffix.lower()
        format_map = {
            '.pdb': 'pdb',
            '.xyz': 'xyz',
            '.poscar': 'poscar',
            '.vasp': 'poscar',
            '.cif': 'cif',
            '.data': 'lammps',
            '.lmp': 'lammps',
            '.gro': 'gro',
            '.gjf': 'gaussian',
            '.com': 'gaussian',
        }
        return format_map.get(ext, 'xyz')

    def _write_pdb(self, structure: Structure, path: Path):
        """写入PDB文件"""
        with open(path, 'w') as f:
            f.write(f"TITLE     {structure.name}\n")
            f.write(f"REMARK    Generated by Modeling\n")

            # 写入CRYST1记录 (如果有cell)
            if structure.cell is not None:
                cell = structure.cell
                if cell.ndim == 1:
                    a, b, c = cell
                else:
                    a, b, c = np.diag(cell)
                f.write(f"CRYST1{a:9.3f}{b:9.3f}{c:9.3f}  90.00  90.00  90.00 P 1\n")

            # 写入原子
            for i, (pos, sym) in enumerate(zip(structure.positions, structure.symbols)):
                atom_name = f"{sym:<4}"
                f.write(
                    f"ATOM  {i+1:5d} {atom_name} MOL     1    "
                    f"{pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}"
                    f"  1.00  0.00          {sym:>2}\n"
                )

            f.write("END\n")

    def _write_xyz(self, structure: Structure, path: Path):
        """写入XYZ文件"""
        with open(path, 'w') as f:
            f.write(f"{structure.n_atoms}\n")
            f.write(f"{structure.name}\n")

            for pos, sym in zip(structure.positions, structure.symbols):
                f.write(f"{sym:2s}  {pos[0]:15.8f}  {pos[1]:15.8f}  {pos[2]:15.8f}\n")

    def _write_poscar(self, structure: Structure, path: Path):
        """写入POSCAR文件"""
        if structure.cell is None:
            raise ValueError("写入POSCAR需要cell信息")

        with open(path, 'w') as f:
            f.write(f"{structure.name}\n")
            f.write("1.0\n")

            # 写入晶格向量
            cell = structure.cell
            if cell.ndim == 1:
                cell = np.diag(cell)

            for row in cell:
                f.write(f"  {row[0]:15.8f}  {row[1]:15.8f}  {row[2]:15.8f}\n")

            # 统计元素
            from collections import Counter
            counts = Counter(structure.symbols)
            elements = list(counts.keys())
            nums = [counts[el] for el in elements]

            f.write("  " + "  ".join(elements) + "\n")
            f.write("  " + "  ".join(map(str, nums)) + "\n")
            f.write("Cartesian\n")

            # 按元素排序写入坐标
            for el in elements:
                for i, sym in enumerate(structure.symbols):
                    if sym == el:
                        pos = structure.positions[i]
                        f.write(f"  {pos[0]:15.8f}  {pos[1]:15.8f}  {pos[2]:15.8f}\n")

    def _write_gaussian(self, structure: Structure, path: Path):
        """
        写入 Gaussian 输入文件 (.gjf/.com)

        通过 Structure.properties 传递 Gaussian 特有参数:
            - gaussian_route: route section (默认 "# HF/6-31G* opt freq")
            - charge: 体系总电荷 (默认 0)
            - multiplicity: 自旋多重度 (默认 1)
            - title: 标题行 (默认 structure.name)
            - link0: dict of Link0 commands, e.g. {"chk": "mol.chk", "nproc": "16", "mem": "16GB"}
            - basis_extra: 自定义基组段 (Gen/GenECP), 追加在坐标之后
        """
        props = structure.properties

        # Link0 commands
        link0 = props.get("link0", {})
        # Route section
        route = props.get("gaussian_route", "# HF/6-31G* opt freq")
        # Title
        title = props.get("title", structure.name or "Generated by Modeling")
        # Charge and multiplicity
        charge = props.get("charge", 0)
        multiplicity = props.get("multiplicity", 1)
        # Extra basis set section
        basis_extra = props.get("basis_extra", "")

        with open(path, 'w', newline='\n') as f:
            # Link0 section
            for key, val in link0.items():
                if key.startswith("%"):
                    f.write(f"{key}={val}\n")
                else:
                    f.write(f"%{key}={val}\n")

            # Route section
            f.write(f"{route}\n")
            f.write("\n")

            # Title section
            f.write(f"{title}\n")
            f.write("\n")

            # Charge and multiplicity
            f.write(f"{charge} {multiplicity}\n")

            # Cartesian coordinates
            for pos, sym in zip(structure.positions, structure.symbols):
                f.write(f" {sym:<2s} {pos[0]:14.8f} {pos[1]:14.8f} {pos[2]:14.8f}\n")

            # Blank line terminates geometry
            f.write("\n")

            # Extra basis set section (Gen/GenECP)
            if basis_extra:
                f.write(f"{basis_extra}\n")
                f.write("\n")

            # Final blank line
            f.write("\n")

    def _write_cif(self, structure: Structure, path: Path):
        """
        写入 CIF 文件

        使用 ASE 写入
        """
        from modeling.tools.ase_tools import ASETools
        ASETools.write_file(structure, str(path), format='cif')

    def _write_lammps(self, structure: Structure, path: Path):
        """
        写入 LAMMPS data 文件

        使用 ASE 写入
        """
        from modeling.tools.ase_tools import ASETools
        ASETools.write_file(structure, str(path), format='lammps-data')

    def _write_gro(self, structure: Structure, path: Path):
        """
        写入 GROMACS GRO 文件

        使用 ASE 写入
        """
        from modeling.tools.ase_tools import ASETools
        ASETools.write_file(structure, str(path), format='gro')


def write_structure(
    structure: Structure,
    filepath: str,
    format: Optional[str] = None
):
    """
    写入结构文件的便捷函数

    Args:
        structure: Structure对象
        filepath: 输出文件路径
        format: 文件格式
    """
    writer = StructureWriter()
    writer.write(structure, filepath, format)
